### ISSUE TITLE
Does not work with twitter videos

### ISSUE THREAD

**Issue by qmr** [wpears/dont#3]

**Comment by qmr** [comment]
Version 66.0.3359.181 (Official Build) (64-bit) Mac

1)  Play twitter video
2)  Change to different tab, video mutes
3)  Scroll down feed, video mutes or stops

**Comment by wpears** [comment]
Hey, thanks for the bug report. This extension was written quite some time ago, before [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)s were in common use. However now, as is the case with Twitter, CSPs are starting to be pretty standard practice. This extension uses an inline-event handler to monkey-patch the default addEventListener method and as such is non-functional anyplace that disallows inline-event handlers from non-whitelisted sources.

I'll look into whether there is a workaround.

**Comment by wpears** [comment]
Version 2.0.0 of the extension uses a different method to execute scripts which works on Twitter. Again, thanks for the bug report :)

re: scrolling stopping the video, that is outside the scope of this extension (though I'd bet one exists cause I, too, find it annoying).
